services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile_local
        environment:
          - PHP_OPCACHE_ENABLE=0
          - PHP_DISPLAY_ERROR=on

    vector-api:
        ports:
            - "8088:8000"

    webserver:
        image: arm64v8/nginx:alpine
        ports:
            - "8080:80"
            - "443:443"

    db:
        image: mysql:8.0
        platform: linux/x86_64
        container_name: db-api-opencart
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: 1234567
        volumes:
            - ./docker/db:/var/lib/mysql
        user: mysql

    redis:
        image: arm64v8/redis
        ports:
            - "6379:6379"

    opensearch:
        image: opensearchproject/opensearch:3
        container_name: opensearch-api-opencart
        environment:
            discovery.type: single-node
            bootstrap.memory_lock: true
            OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
            OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${SEARCH_API_KEY}
        ports:
            - 9200:9200
            - 9600:9600

    hunspell-setup:
        image: alpine:latest

    opensearch-dashboards:
        image: opensearchproject/opensearch-dashboards:3
        container_name: opensearch-dashboards
        ports:
          - 5601:5601
        expose:
          - '5601'
        environment:
          OPENSEARCH_HOSTS: https://opensearch-api-opencart:9200
          OPENSEARCH_USERNAME: ${SEARCH_USER}
          OPENSEARCH_PASSWORD: ${SEARCH_API_KEY}
        networks:
          - api
        depends_on:
          - opensearch

    adminer:
        image: arm64v8/adminer
        restart: unless-stopped
        ports:
            - 8000:8080

volumes:
    opensearch-data:
