services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: digitalocean.com/php
        container_name: php-api-opencart
        platform: linux/amd64
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www
        environment:
            - PHP_OPCACHE_ENABLE=1
            - PHP_MEMORY_LIMIT=128M
            - PHP_MAX_EXECUTION_TIME=300
            - PHP_UPLOAD_MAX_FILESIZE=64M
            - PHP_POST_MAX_SIZE=64M
            - PHP_DISPLAY_ERROR=off
        depends_on:
            - redis
        networks:
            - api

    vector-api:
        build:
            context: .
            dockerfile: docker/embedder/Dockerfile
        container_name: vector-api-opencart
        environment:
            API_TOKEN: ${API_TOKEN}
            SEARCH_EMBEDDING_MODEL: ${SEARCH_EMBEDDING_MODEL}
        volumes:
            -  ./docker/embedder/app:/app
        restart: unless-stopped
        networks:
            - api

    webserver:
        image: nginx:alpine
        container_name: webserver-api-opencart
        platform: linux/amd64
        restart: unless-stopped
        tty: true
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.local.conf/:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - api

    redis:
        image: redis
        container_name: redis-api-opencart
        platform: linux/amd64
        command: redis-server --requirepass ${REDIS_PASSWORD}
        restart: unless-stopped
        networks:
            - api

    opensearch:
        image: opensearchproject/opensearch:3
        container_name: opensearch-api-opencart
        platform: linux/amd64
        environment:
            discovery.type: single-node
            bootstrap.memory_lock: true
            OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
            OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${SEARCH_API_KEY}
        command: |
            bash -c "
            if [ ! -d '/usr/share/opensearch/plugins/opensearch-knn' ]; then
                /usr/share/opensearch/bin/opensearch-plugin install opensearch-knn --batch
            fi &&
            if [ ! -d '/usr/share/opensearch/plugins/analysis-phonetic' ]; then
                /usr/share/opensearch/bin/opensearch-plugin install analysis-phonetic --batch
            fi &&
                /usr/share/opensearch/opensearch-docker-entrypoint.sh opensearch
            "
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./docker/opensearch/data:/usr/share/opensearch/data
            - ./docker/opensearch/hunspell:/usr/share/opensearch/config/hunspell
            - opensearch-data:/usr/share/opensearch/data
        networks:
            - api

    hunspell-setup:
        image: alpine:latest
        container_name: hunspell-setup
        volumes:
            - ./docker/opensearch/hunspell:/hunspell
        command: |
            sh -c "
              apk add --no-cache wget unzip &&
              mkdir -p /hunspell/ru_RU /hunspell/uk_UA &&
              cd /hunspell/ru_RU &&
              wget -O uk_UA.dic https://raw.githubusercontent.com/LibreOffice/dictionaries/master/ru_RU/ru_RU.dic &&
              wget -O uk_UA.aff https://raw.githubusercontent.com/LibreOffice/dictionaries/master/ru_RU/ru_RU.aff &&
              cd /hunspell/uk_UA &&
              wget -O uk_UA.dic https://raw.githubusercontent.com/LibreOffice/dictionaries/master/uk_UA/uk_UA.dic &&
              wget -O uk_UA.aff https://raw.githubusercontent.com/LibreOffice/dictionaries/master/uk_UA/uk_UA.aff
            "
        depends_on:
            - opensearch

networks:
    api:
        driver: bridge

volumes:
    opensearch-data:
