services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: digitalocean.com/php
        container_name: php-api-opencart
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis

    webserver:
        image: arm64v8/nginx:alpine
        container_name: webserver-api-opencart
        restart: unless-stopped
        tty: true
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.local.conf/:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
            - "443:443"
        depends_on:
            - app

    db:
        image: mysql:8.0
        platform: linux/x86_64
        container_name: db-api-opencart
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: 1234567
        volumes:
            - ./docker/db:/var/lib/mysql
        user: mysql

    redis:
        image: arm64v8/redis
        container_name: redis-api-opencart
        command: redis-server --requirepass ${REDIS_PASSWORD}
        restart: unless-stopped
        ports:
            - "6379:6379"

    adminer:
        image: arm64v8/adminer
        restart: unless-stopped
        ports:
            - 8000:8080
